INSERT INTO `{prefix}countries` (`id`, `name`, `iso`, `iso2`, `iso4217`, `tax`, `display`, `eu`) VALUES
	(1, 'Afghanistan', 'AFG', 'AF', '004', '', 'yes', 'no'),
	(2, 'Albania', 'ALB', 'AL', '008', '', 'yes', 'no'),
	(3, 'Algeria', 'DZA', 'DZ', '012', '', 'yes', 'no'),
	(4, 'Andorra', 'AND', 'AD', '20', '', 'yes', 'no'),
	(5, 'Angola', 'AGO', 'AO', '024', '', 'yes', 'no'),
	(6, 'Antigua and Barbuda', 'ATG', 'AG', '028', '', 'yes', 'no'),
	(7, 'Argentina', 'ARG', 'AR', '032', '', 'yes', 'no'),
	(8, 'Armenia', 'ARM', 'AM', '051', '', 'yes', 'no'),
	(9, 'Australia', 'AUS', 'AU', '036', '', 'yes', 'no'),
	(10, 'Austria', 'AUT', 'AT', '040', '', 'yes', 'no'),
	(11, 'Azerbaijan', 'AZE', 'AZ', '031', '', 'yes', 'no'),
	(12, 'Bahamas', 'BHS', 'BS', '044', '', 'yes', 'no'),
	(13, 'Bahrain', 'BHR', 'BH', '048', '', 'yes', 'no'),
	(14, 'Bangladesh', 'BGD', 'BD', '050', '', 'yes', 'no'),
	(15, 'Barbados', 'BRB', 'BB', '052', '', 'yes', 'no'),
	(16, 'Belarus', 'BLR', 'BY', '112', '', 'yes', 'no'),
	(17, 'Belgium', 'BEL', 'BE', '056', '', 'yes', 'no'),
	(18, 'Belize', 'BLZ', 'BZ', '084', '', 'yes', 'no'),
	(19, 'Benin', 'BEN', 'BJ', '204', '', 'yes', 'no'),
	(20, 'Bhutan', 'BTN', 'BT', '064', '', 'yes', 'no'),
	(21, 'Bolivia', 'BOL', 'BO', '068', '', 'yes', 'no'),
	(22, 'Bosnia and Herzegovina', 'BIH', 'BA', '070', '', 'yes', 'no'),
	(23, 'Botswana', 'BWA', 'BW', '072', '', 'yes', 'no'),
	(24, 'Brazil', 'BRA', 'BR', '076', '', 'yes', 'no'),
	(25, 'Brunei', 'BRN', 'BN', '096', '', 'yes', 'no'),
	(26, 'Bulgaria', 'BGR', 'BG', '100', '', 'yes', 'no'),
	(27, 'Burkina Faso', 'BFA', 'BF', '854', '', 'yes', 'no'),
	(28, 'Burundi', 'BDI', 'BI', '108', '', 'yes', 'no'),
	(29, 'Cambodia', 'KHM', 'KH', '116', '', 'yes', 'no'),
	(30, 'Cameroon', 'CMR', 'CM', '120', '', 'yes', 'no'),
	(31, 'Canada', 'CAN', 'CA', '124', '', 'yes', 'no'),
	(32, 'Cape Verde', 'CPV', 'CV', '132', '', 'yes', 'no'),
	(33, 'Central African Republic', 'CAF', 'CF', '140', '', 'yes', 'no'),
	(34, 'Chad', 'TCD', 'TD', '148', '', 'yes', 'no'),
	(35, 'Chile', 'CHL', 'CL', '152', '', 'yes', 'no'),
	(36, 'China', 'CHN', 'CN', '156', '', 'yes', 'no'),
	(37, 'Colombia', 'COL', 'CO', '170', '', 'yes', 'no'),
	(38, 'Comoros', 'COM', 'KM', '174', '', 'yes', 'no'),
	(39, 'Congo', 'COG', 'CG', '178', '', 'yes', 'no'),
	(41, 'Costa Rica', 'CRI', 'CK', '184', '', 'yes', 'no'),
	(42, 'Cote d\'Ivoire', 'CIV', 'CR', '188', '', 'yes', 'no'),
	(43, 'Croatia', 'HRV', 'HR', '191', '', 'yes', 'no'),
	(44, 'Cuba', 'CUB', 'CU', '192', '', 'yes', 'no'),
	(45, 'Cyprus', 'CYP', 'CY', '196', '', 'yes', 'no'),
	(46, 'Czech Republic', 'CZE', 'CZ', '203', '', 'yes', 'no'),
	(47, 'Denmark', 'DNK', 'DK', '208', '', 'yes', 'no'),
	(48, 'Djibouti', 'DJI', 'DJ', '262', '', 'yes', 'no'),
	(49, 'Dominica', 'DMA', 'DM', '212', '', 'yes', 'no'),
	(50, 'Dominican Republic', 'DOM', 'DO', '214', '', 'yes', 'no'),
	(51, 'Ecuador', 'ECU', 'EC', '218', '', 'yes', 'no'),
	(52, 'Egypt', 'EGY', 'EG', '818', '', 'yes', 'no'),
	(53, 'El Salvador', 'SLV', 'SV', '222', '', 'yes', 'no'),
	(54, 'Equatorial Guinea', 'GNQ', 'GQ', '226', '', 'yes', 'no'),
	(55, 'Eritrea', 'ERI', 'ER', '232', '', 'yes', 'no'),
	(56, 'Estonia', 'EST', 'EE', '233', '', 'yes', 'no'),
	(57, 'Ethiopia', 'ETH', 'ET', '231', '', 'yes', 'no'),
	(58, 'Fiji', 'FJI', 'FJ', '242', '', 'yes', 'no'),
	(59, 'Finland', 'FIN', 'FI', '246', '', 'yes', 'no'),
	(60, 'France', 'FRA', 'FR', '250', '', 'yes', 'no'),
	(61, 'Gabon', 'GAB', 'GA', '266', '', 'yes', 'no'),
	(62, 'Gambia', 'GMB', 'GM', '270', '', 'yes', 'no'),
	(63, 'Georgia', 'GEO', 'GE', '268', '', 'yes', 'no'),
	(64, 'Germany', 'DEU', 'DE', '276', '', 'yes', 'no'),
	(65, 'Ghana', 'GHA', 'GH', '288', '', 'yes', 'no'),
	(66, 'Greece', 'GRC', 'GR', '300', '', 'yes', 'no'),
	(67, 'Grenada', 'GRD', 'GD', '308', '', 'yes', 'no'),
	(68, 'Guatemala', 'GTM', 'GT', '320', '', 'yes', 'no'),
	(69, 'Guinea', 'GIN', 'GN', '324', '', 'yes', 'no'),
	(70, 'Guinea-Bissau', 'GNB', 'GW', '624', '', 'yes', 'no'),
	(71, 'Guyana', 'GUY', 'GY', '328', '', 'yes', 'no'),
	(72, 'Haiti', 'HTI', 'HT', '332', '', 'yes', 'no'),
	(73, 'Honduras', 'HND', 'HN', '340', '', 'yes', 'no'),
	(74, 'Hungary', 'HUN', 'HU', '348', '', 'yes', 'no'),
	(75, 'Iceland', 'ISL', 'IS', '352', '', 'yes', 'no'),
	(76, 'India', 'IND', 'IN', '356', '', 'yes', 'no'),
	(77, 'Indonesia', 'IDN', 'ID', '360', '', 'yes', 'no'),
	(78, 'Iran', 'IRN', 'IR', '364', '', 'yes', 'no'),
	(79, 'Iraq', 'IRQ', 'IQ', '368', '', 'yes', 'no'),
	(80, 'Ireland', 'IRL', 'IE', '372', '', 'yes', 'no'),
	(81, 'Israel', 'ISR', 'IL', '376', '', 'yes', 'no'),
	(82, 'Italy', 'ITA', 'IT', '380', '', 'yes', 'no'),
	(83, 'Jamaica', 'JAM', 'JM', '388', '', 'yes', 'no'),
	(84, 'Japan', 'JPN', 'JP', '392', '', 'yes', 'no'),
	(85, 'Jordan', 'JOR', 'JO', '400', '', 'yes', 'no'),
	(86, 'Kazakhstan', 'KAZ', 'KZ', '398', '', 'yes', 'no'),
	(87, 'Kenya', 'KEN', 'KE', '404', '', 'yes', 'no'),
	(88, 'Kiribati', 'KIR', 'KI', '296', '', 'yes', 'no'),
	(89, 'South Korea', 'KOR', 'KR', '410', '', 'yes', 'no'),
	(90, 'North Korea', 'PRK', 'KP', '408', '', 'yes', 'no'),
	(91, 'Kuwait', 'KWT', 'KW', '414', '', 'yes', 'no'),
	(92, 'Kyrgyzstan', 'KGZ', 'KG', '417', '', 'yes', 'no'),
	(93, 'Laos', 'LAO', 'LA', '418', '', 'yes', 'no'),
	(94, 'Latvia', 'LVA', 'LV', '428', '', 'yes', 'no'),
	(95, 'Lebanon', 'LBN', 'LB', '422', '', 'yes', 'no'),
	(96, 'Lesotho', 'LSO', 'LS', '426', '', 'yes', 'no'),
	(97, 'Liberia', 'LBR', 'LR', '430', '', 'yes', 'no'),
	(98, 'Libya', 'LBY', 'LY', '434', '', 'yes', 'no'),
	(99, 'Liechtenstein', 'LIE', 'LI', '438', '', 'yes', 'no'),
	(100, 'Lithuania', 'LTU', 'LT', '440', '', 'yes', 'no'),
	(101, 'Luxembourg', 'LUX', 'LU', '442', '', 'yes', 'no'),
	(102, 'Macedonia', 'MKD', 'MK', '807', '', 'yes', 'no'),
	(103, 'Madagascar', 'MDG', 'MG', '450', '', 'yes', 'no'),
	(104, 'Malawi', 'MWI', 'MW', '454', '', 'yes', 'no'),
	(105, 'Malaysia', 'MYS', 'MY', '458', '', 'yes', 'no'),
	(106, 'Maldives', 'MDV', 'MV', '462', '', 'yes', 'no'),
	(107, 'Mali', 'MLI', 'ML', '466', '', 'yes', 'no'),
	(108, 'Malta', 'MLT', 'MT', '470', '', 'yes', 'no'),
	(109, 'Marshall Islands', 'MHL', 'MH', '584', '', 'yes', 'no'),
	(110, 'Mauritania', 'MRT', 'MR', '478', '', 'yes', 'no'),
	(111, 'Mauritius', 'MUS', 'MU', '480', '', 'yes', 'no'),
	(112, 'Mexico', 'MEX', 'MX', '484', '', 'yes', 'no'),
	(113, 'Micronesia', 'FSM', 'FM', '583', '', 'yes', 'no'),
	(114, 'Moldova', 'MDA', 'MD', '498', '', 'yes', 'no'),
	(115, 'Monaco', 'MCO', 'MC', '492', '', 'yes', 'no'),
	(116, 'Mongolia', 'MNG', 'MN', '496', '', 'yes', 'no'),
	(117, 'Montenegro', 'MNE', 'ME', '499', '', 'yes', 'no'),
	(118, 'Morocco', 'MAR', 'MA', '504', '', 'yes', 'no'),
	(119, 'Mozambique', 'MOZ', 'MZ', '508', '', 'yes', 'no'),
	(120, 'Myanmar (Burma)', 'MMR', 'MM', '104', '', 'yes', 'no'),
	(121, 'Namibia', 'NAM', 'NA', '516', '', 'yes', 'no'),
	(122, 'Nauru', 'NRU', 'NR', '520', '', 'yes', 'no'),
	(123, 'Nepal', 'NPL', 'NP', '524', '', 'yes', 'no'),
	(124, 'Netherlands', 'NLD', 'NL', '528', '', 'yes', 'no'),
	(125, 'New Zealand', 'NZL', 'NZ', '554', '', 'yes', 'no'),
	(126, 'Nicaragua', 'NIC', 'NI', '558', '', 'yes', 'no'),
	(127, 'Niger', 'NER', 'NE', '562', '', 'yes', 'no'),
	(128, 'Nigeria', 'NGA', 'NG', '566', '', 'yes', 'no'),
	(129, 'Norway', 'NOR', 'NO', '578', '', 'yes', 'no'),
	(130, 'Oman', 'OMN', 'OM', '512', '', 'yes', 'no'),
	(131, 'Pakistan', 'PAK', 'PK', '586', '', 'yes', 'no'),
	(132, 'Palau', 'PLW', 'PW', '585', '', 'yes', 'no'),
	(133, 'Panama', 'PAN', 'PA', '591', '', 'yes', 'no'),
	(134, 'Papua New Guinea', 'PNG', 'PG', '598', '', 'yes', 'no'),
	(135, 'Paraguay', 'PRY', 'PY', '600', '', 'yes', 'no'),
	(136, 'Peru', 'PER', 'PE', '604', '', 'yes', 'no'),
	(137, 'Philippines', 'PHL', 'PH', '608', '', 'yes', 'no'),
	(138, 'Poland', 'POL', 'PL', '616', '', 'yes', 'no'),
	(139, 'Portugal', 'PRT', 'PT', '620', '', 'yes', 'no'),
	(140, 'Qatar', 'QAT', 'QA', '634', '', 'yes', 'no'),
	(141, 'Romania', 'ROU', 'RO', '642', '', 'yes', 'no'),
	(142, 'Russian Federation', 'RUS', 'RU', '643', '', 'yes', 'no'),
	(143, 'Rwanda', 'RWA', 'RW', '646', '', 'yes', 'no'),
	(144, 'Saint Kitts and Nevis', 'KNA', 'KN', '659', '', 'yes', 'no'),
	(145, 'Saint Lucia', 'LCA', 'LC', '662', '', 'yes', 'no'),
	(146, 'Saint Vincent and the Grenadines', 'VCT', 'VC', '670', '', 'yes', 'no'),
	(147, 'Samoa', 'WSM', 'WS', '882', '', 'yes', 'no'),
	(148, 'San Marino', 'SMR', 'SM', '674', '', 'yes', 'no'),
	(149, 'Sao Tome and Principe', 'STP', 'ST', '678', '', 'yes', 'no'),
	(150, 'Saudi Arabia', 'SAU', 'SA', '682', '', 'yes', 'no'),
	(151, 'Senegal', 'SEN', 'SN', '686', '', 'yes', 'no'),
	(152, 'Serbia', 'SRB', 'RS', '688', '', 'yes', 'no'),
	(153, 'Seychelles', 'SYC', 'SC', '690', '', 'yes', 'no'),
	(154, 'Sierra Leone', 'SLE', 'SL', '694', '', 'yes', 'no'),
	(155, 'Singapore', 'SGP', 'SG', '702', '', 'yes', 'no'),
	(156, 'Slovakia', 'SVK', 'SK', '703', '', 'yes', 'no'),
	(157, 'Slovenia', 'SVN', 'SI', '705', '', 'yes', 'no'),
	(159, 'Somalia', 'SOM', 'SO', '706', '', 'yes', 'no'),
	(160, 'South Africa', 'ZAF', 'ZA', '710', '', 'yes', 'no'),
	(161, 'Spain', 'ESP', 'ES', '724', '', 'yes', 'no'),
	(162, 'Sri Lanka', 'LKA', 'LK', '144', '', 'yes', 'no'),
	(163, 'Sudan', 'SDN', 'SD', '736', '', 'yes', 'no'),
	(164, 'Suriname', 'SUR', 'SR', '740', '', 'yes', 'no'),
	(165, 'Swaziland', 'SWZ', 'SZ', '748', '', 'yes', 'no'),
	(166, 'Sweden', 'SWE', 'SE', '752', '', 'yes', 'no'),
	(167, 'Switzerland', 'CHE', 'CH', '756', '', 'yes', 'no'),
	(168, 'Syrian Arab Republic', 'SYR', 'SY', '760', '', 'yes', 'no'),
	(169, 'Tajikistan', 'TJK', 'TJ', '762', '', 'yes', 'no'),
	(170, 'Tanzania', 'TZA', 'TZ', '834', '', 'yes', 'no'),
	(171, 'Thailand', 'THA', 'TH', '764', '', 'yes', 'no'),
	(172, 'Timor-Leste (East Timor)', 'TLS', 'TL', '626', '', 'yes', 'no'),
	(173, 'Togo', 'TGO', 'TG', '768', '', 'yes', 'no'),
	(174, 'Tonga', 'TON', 'TO', '776', '', 'yes', 'no'),
	(175, 'Trinidad and Tobago', 'TTO', 'TT', '780', '', 'yes', 'no'),
	(176, 'Tunisia', 'TUN', 'TN', '788', '', 'yes', 'no'),
	(177, 'Turkey', 'TUR', 'TR', '792', '', 'yes', 'no'),
	(178, 'Turkmenistan', 'TKM', 'TM', '795', '', 'yes', 'no'),
	(179, 'Tuvalu', 'TUV', 'TV', '798', '', 'yes', 'no'),
	(180, 'Uganda', 'UGA', 'UG', '800', '', 'yes', 'no'),
	(181, 'Ukraine', 'UKR', 'UA', '804', '', 'yes', 'no'),
	(182, 'United Arab Emirates', 'ARE', 'AE', '784', '', 'yes', 'no'),
	(183, 'United Kingdom', 'GBR', 'GB', '826', '', 'yes', 'no'),
	(184, 'United States', 'USA', 'US', '840', '', 'yes', 'no'),
	(185, 'Uruguay', 'URY', 'UY', '858', '', 'yes', 'no'),
	(186, 'Uzbekistan', 'UZB', 'UZ', '860', '', 'yes', 'no'),
	(187, 'Vanuatu', 'VUT', 'VU', '548', '', 'yes', 'no'),
	(188, 'Vatican City', 'VAT', 'VA', '336', '', 'yes', 'no'),
	(189, 'Venezuela', 'VEN', 'VE', '862', '', 'yes', 'no'),
	(190, 'Vietnam', 'VNM', 'VN', '704', '', 'yes', 'no'),
	(191, 'Yemen', 'YEM', 'YE', '887', '', 'yes', 'no'),
	(192, 'Zambia', 'ZMB', 'ZM', '894', '', 'yes', 'no'),
	(193, 'Zimbabwe', 'ZWE', 'ZW', '716', '', 'yes', 'no'),
	(202, 'Christmas Island', 'CXR', 'CX', '162', '', 'yes', 'no'),
	(203, 'Cocos (Keeling) Islands', 'CCK', 'CC', '166', '', 'yes', 'no'),
	(205, 'Heard Island and McDonald Islands', 'HMD', 'HM', '334', '', 'yes', 'no'),
	(206, 'Norfolk Island', 'NFK', 'NF', '574', '', 'yes', 'no'),
	(207, 'New Caledonia', 'NCL', 'NC', '540', '', 'yes', 'no'),
	(208, 'French Polynesia', 'PYF', 'PF', '258', '', 'yes', 'no'),
	(209, 'Mayotte', 'MYT', 'YT', '175', '', 'yes', 'no'),
	(210, 'Saint Barthelemy', 'GLP', 'BL', '652', '', 'yes', 'no'),
	(211, 'Saint Martin', 'GLP', 'MF', '663', '', 'yes', 'no'),
	(212, 'Saint Pierre and Miquelon', 'SPM', 'PM', '666', '', 'yes', 'no'),
	(213, 'Wallis and Futuna', 'WLF', 'WF', '876', '', 'yes', 'no'),
	(214, 'French Southern and Antarctic Lands', 'ATF', 'TF', '260', '', 'yes', 'no'),
	(216, 'Bouvet Island', 'BVT', 'BV', '074', '', 'yes', 'no'),
	(217, 'Cook Islands', 'COK', 'CD', '180', '', 'yes', 'no'),
	(218, 'Niue', 'NIU', 'NU', '570', '', 'yes', 'no'),
	(219, 'Tokelau', 'TKL', 'TK', '772', '', 'yes', 'no'),
	(220, 'Guernsey', 'GGY', 'GG', '831', '', 'yes', 'no'),
	(221, 'Isle of Man', 'IMN', 'IM', '833', '', 'yes', 'no'),
	(222, 'Jersey', 'JEY', 'JE', '832', '', 'yes', 'no'),
	(223, 'Anguilla', 'AIA', 'AI', '660', '', 'yes', 'no'),
	(224, 'Bermuda', 'BMU', 'BM', '060', '', 'yes', 'no'),
	(225, 'British Indian Ocean Territory', 'IOT', 'IO', '086', '', 'yes', 'no'),
	(227, 'British Virgin Islands', 'VGB', 'VG', '092', '', 'yes', 'no'),
	(228, 'Cayman Islands', 'CYM', 'KY', '136', '', 'yes', 'no'),
	(229, 'Falkland Islands (Islas Malvinas)', 'FLK', 'FK', '238', '', 'yes', 'no'),
	(230, 'Gibraltar', 'GIB', 'GI', '292', '', 'yes', 'no'),
	(231, 'Montserrat', 'MSR', 'MS', '500', '', 'yes', 'no'),
	(232, 'Pitcairn Islands', 'PCN', 'PN', '612', '', 'yes', 'no'),
	(233, 'Saint Helena', 'SHN', 'SH', '654', '', 'yes', 'no'),
	(234, 'South Georgia & South Sandwich Islands', 'SGS', 'GS', '239', '', 'yes', 'no'),
	(235, 'Turks and Caicos Islands', 'TCA', 'TC', '796', '', 'yes', 'no'),
	(236, 'Northern Mariana Islands', 'MNP', 'MP', '580', '', 'yes', 'no'),
	(237, 'Puerto Rico', 'PRI', 'PR', '630', '', 'yes', 'no'),
	(238, 'American Samoa', 'ASM', 'AS', '016', '', 'yes', 'no'),
	(240, 'Guam', 'GUM', 'GU', '316', '', 'yes', 'no'),
	(248, 'US Virgin Islands', 'VIR', 'VI', '850', '', 'yes', 'no'),
	(250, 'Hong Kong', 'HKG', 'HK', '344', '', 'yes', 'no'),
	(251, 'Macau', 'MAC', 'MO', '446', '', 'yes', 'no'),
	(252, 'Faroe Islands', 'FRO', 'FO', '234', '', 'yes', 'no'),
	(253, 'Greenland', 'GRL', 'GL', '304', '', 'yes', 'no'),
	(254, 'French Guiana', 'GUF', 'GF', '254', '', 'yes', 'no'),
	(255, 'Guadeloupe', 'GLP', 'GP', '312', '', 'yes', 'no'),
	(256, 'Martinique', 'MTQ', 'MQ', '474', '', 'yes', 'no'),
	(257, 'Reunion', 'REU', 'RE', '638', '', 'yes', 'no'),
	(259, 'Aruba', 'ABW', 'AW', '533', '', 'yes', 'no'),
	(260, 'Netherlands Antilles', 'ANT', 'AN', '530', '', 'yes', 'no'),
	(261, 'Svalbard and Jan Mayen', 'SJM', 'SJ', '744', '', 'yes', 'no'),
	(264, 'Australian Antarctic Territory', 'ATA', 'AQ', '010', '', 'yes', 'no')